### PR TITLE
Use computed value in the reason message for non-static positions

### PR DESCRIPTION
**Pull request by giuseppeg**

### CODE REVIEW

**Comment by giuseppeg** [comment]
hi @gwwar, want to merge this?

**Comment by gwwar** [comment]
Oh nice catch @giuseppeg! Sorry I didn't see the ping earlier.

**Comment by giuseppeg** [comment]
no worries @gwwar, thank you!!

**Comment by gwwar** [comment]
👍 Fix published to v1.0.1. Thanks @giuseppeg!

**Pull request merged**
